/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/main.jsx",
    "./src/App.jsx",
    "./src/components/**/*.{js,jsx}",
    "./src/pages/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#11131b',
        'surface-dim': '#11131b',
        'surface-bright': '#373942',
        'surface-container-lowest': '#0c0e16',
        'surface-container-low': '#191b23',
        'surface-container': '#1d1f27',
        'surface-container-high': '#282a32',
        'surface-container-highest': '#32343d',
        'on-surface': '#e1e2ed',
        'on-surface-variant': '#c3c6d7',
        'inverse-surface': '#e1e2ed',
        'inverse-on-surface': '#2e3039',
        outline: '#8d90a0',
        'outline-variant': '#434655',
        'surface-tint': '#b4c5ff',
        primary: '#b4c5ff',
        'on-primary': '#002a78',
        'primary-container': '#2563eb',
        'on-primary-container': '#eeefff',
        'inverse-primary': '#0053db',
        secondary: '#4cd7f6',
        'on-secondary': '#003640',
        'secondary-container': '#03b5d3',
        'on-secondary-container': '#00424e',
        tertiary: '#ffb596',
        'on-tertiary': '#581e00',
        'tertiary-container': '#bc4800',
        'on-tertiary-container': '#ffede6',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed': '#acedff',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'on-secondary-fixed-variant': '#004e5c',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        background: '#11131b',
        'on-background': '#e1e2ed',
        'surface-variant': '#32343d',
      },
      fontFamily: {
        heading: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
